export const countries = [
     "United States",
     "Argentina",
     "Australia",
     "Bangladesh",
     "Brazil",
     "Canada",
     "Egypt",
     "France",
     "Germany",
     "India",
     "Indonesia",
     "Italy",
     "Japan",
     "Mexico",
     "Nigeria",
     "Pakistan",
     "Philippines",
     "Russia",
     "South Africa",
     "South Korea",
     "Spain",
     "Turkey",
     "United Kingdom",
     "Vietnam",
];
