export const developers = [
     "Front End Developer",
     "Back End Developer",
     "Full Stack Developer",
     "Mobile App Developer",
     "Web Developer",
     "DevOps Engineer",
     "Data Scientist",
     "Machine Learning Engineer",
     "AI Developer",
     "Game Developer",
     "Embedded Systems Developer",
     "Cloud Architect",
     "UI/UX Developer",
     "Database Developer",
     "Security Engineer",
     "QA/Test Engineer",
     "Big Data Engineer",
     "Blockchain Developer",
     "AR/VR Developer",
];
